_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 1
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.5
            "5": 0.18.5
            "6": 4.32.1
            "8":
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
batch_size:
    value: 64
dropout_rate:
    value: 0.2
epochs:
    value: 10
hidden_layers:
    value:
        - 128
        - 64
learning_rate:
    value: 0.01
